---
title: "Final Proposal"
author: "Chloe Wong, Hanwen Yang, Junhao Lai"
date: '2024-03-01'
output:
  pdf_document: 
    number_sections: true
---

```{r setup, include=FALSE}
# some useful settings
knitr::opts_chunk$set(echo = TRUE, tidy.opts = list(width.cutoff = 55), tidy = TRUE, fig.align="center")
```

# Introduction 

## Part (a)

```{r}
#setwd("/Users/laix1/OneDrive/Desktop/Final_Proposal")
knitr::opts_knit$set(root.dir = 'C:/Users/laix1/OneDrive/Desktop/Final_Proposal/ECON124')

library(haven)

covid_data <- data.frame(read_dta("C19CS Data.dta"))

dim(covid_data)


```




## Part (b)



# Data



# Methodology 


# Main Results
we first did a raw correlation on the smoking status and COVID-19 positivity 
```{r}

SM_data <- na.omit(covid_data[,c(201,851),]) #
head(SM_data)

naive_SM_OLS <- glm(t5_cov_self_t ~ t0_smoke, data = SM_data)
summary(naive_SM_OLS)



```
A person what has an active smoking status is associated with a 2.4% increased in the chance of tested positive for COVID-19 past month.

